# -*- mode: ruby -*-
# vi: set ft=ruby :

# Case-sensitive volume in host for building Linux
# HOST_BUILD_VOLUME = "/Volumes/Build01"
HOST_BUILD_VOLUME = "../"

# This is the mount point for the sync_folders in the VM
SRCMOUNT = "/opt/src"
LOCALDEV = "/local-dev"
BLDMOUNT = "/build"

CWD = File.dirname(File.expand_path(__FILE__))

DATA_DISK="../data-disk.vdi"

# -----------------------------------------------------------------------------
# Vagrant definition
# -----------------------------------------------------------------------------
Vagrant.require_version ">= 1.7.4"
Vagrant.configure("2") do |config|

  # disable rsyncing folders
  config.vm.synced_folder ".", "/vagrant", disabled: true

  # common settings: ssh login
  #config.ssh.username = "vagrant"
  #config.ssh.forward_agent = true

  required_plugins = %w(vagrant-vbguest vagrant-disksize)
  config.disksize.size = "40GB"

  # -----------------------------------
  # 1. VM for anbox-foilplanet develepment
  # -----------------------------------
  config.vm.define "detnet_rdma" do |detnet_rdma|
    detnet_rdma.vm.box = "ubuntu/focal64"
    
    # shared folders
    # detnet_rdma.vm.synced_folder ENV.fetch('LOCALDEVDIR', ".."), "#{LOCALDEV}"
    detnet_rdma.vm.synced_folder "..", "#{LOCALDEV}"
    # detnet_rdma.vm.synced_folder "..", "#{SRCMOUNT}"
    detnet_rdma.vm.synced_folder "#{HOST_BUILD_VOLUME}", "#{BLDMOUNT}"

    # provisioning
    detnet_rdma.vm.provision "shell", inline: <<-SCRIPT
      set -x
      # timezone
      export TZ=Asia/Shanghai
    
      # setup scripts
      cd #{LOCALDEV}/devenv/ubuntu20
      ./setup_box.sh
      ./setup_python.sh
      ./setup_ns3.sh
    SCRIPT

    # VirtualBox
    detnet_rdma.vm.hostname = "detnet-rdma"
    detnet_rdma.vm.network "public_network", nic_type: "virtio", bridge: ""
    # -- web-ui --
    detnet_rdma.vm.network "forwarded_port", guest: 8080,  host: 18080
    # -- ssh for qemu --
    #detnet_rdma.vm.network "forwarded_port", guest: 30022,  host: 30022
    # -- vnc for qemu --
    #detnet_rdma.vm.network "forwarded_port", guest: 5904,   host: 5904

    detnet_rdma.vm.provider "virtualbox" do |vb|
      vb.name = "machine-detnet-rdma"
      vb.cpus = 2
      vb.memory = 4096
      vb.default_nic_type = "virtio"
      vb.customize ['modifyvm', :id, '--description', 'VM for AI NVR devel']
      vb.customize ['modifyvm', :id, '--nictype1', 'virtio']

      # Add a second disk (maximum 100G) for temporay output and data
      #unless File.exist?(DATA_DISK)
      # vb.customize ['createhd', '--filename', DATA_DISK, '--size', 100 * 1024]
      #end
      #vb.customize ['storageattach', :id, '--storagectl', 'SCSI',
      #  '--port', 2, '--device', 0, '--type', 'hdd', '--medium', DATA_DISK]
    end
  end

end
